-- ==============================================================================
-- SYNTHETIC DEMO DATA — ALL CRIME RECORDS SHOWN ARE FICTIONAL AND CREATED FOR DEMONSTRATION PURPOSES ONLY.
-- Total records: 105
-- Cities: Chennai, Mumbai, Delhi, Bengaluru, Hyderabad, Kolkata, Pune, Kochi, Coimbatore, Madurai
-- Crime Types: Theft, Mobile Phone Theft, Vehicle Theft, Robbery, Burglary, Assault, Cybercrime, Fraud, Missing Person, Vandalism, Drug-related offences
-- ==============================================================================

INSERT INTO crime_records (case_id, crime_type, location, incident_date, description, victim_age, suspect_age, status, severity) VALUES
('CASE-1001', 'Mobile Phone Theft', 'Chennai', '2026-05-14', 'A mobile phone was reported stolen from a commuter while travelling through a crowded railway station.', 21, NULL, 'Open', 'Medium'),
('CASE-1002', 'Cybercrime', 'Bengaluru', '2026-06-03', 'A resident reported losing money after receiving a fraudulent message requesting banking information and OTP.', 42, NULL, 'Under Investigation', 'High'),
('CASE-1003', 'Vehicle Theft', 'Mumbai', '2026-04-21', 'A motorcycle was reported missing from a residential parking area during the night.', 35, NULL, 'Open', 'Medium'),
('CASE-1004', 'Robbery', 'Delhi', '2026-01-18', 'Two unidentified individuals threatened a shopkeeper with a weapon near the central market and fled with cash.', 50, 26, 'Under Investigation', 'High'),
('CASE-1005', 'Theft', 'Mumbai', '2026-06-12', 'A backpack containing a work laptop, wallet, and personal documents was taken from an office lobby while unattended.', 29, NULL, 'Open', 'Low'),
('CASE-1006', 'Mobile Phone Theft', 'Chennai', '2026-03-09', 'Smartphone disappeared from a commuter bag while boarding the suburban train during peak morning hours.', 24, NULL, 'Open', 'Medium'),
('CASE-1007', 'Theft', 'Mumbai', '2026-07-21', 'Gold ornaments were reported stolen from an unattended handbag inside a retail clothing outlet.', 38, 30, 'Under Investigation', 'Medium'),
('CASE-1008', 'Fraud', 'Hyderabad', '2025-11-15', 'Victim fell prey to an online investment scheme promising doubling of money within a month through a dubious mobile application.', 47, NULL, 'Under Investigation', 'High'),
('CASE-1009', 'Burglary', 'Pune', '2026-02-14', 'Break-in reported at a locked suburban villa during holiday weekend; electronic gadgets and silverware missing.', 58, NULL, 'Open', 'High'),
('CASE-1010', 'Assault', 'Kolkata', '2026-05-30', 'Physical altercation broke out outside an eatery following a parking dispute resulting in minor injuries.', 32, 28, 'Closed', 'Medium'),

('CASE-1011', 'Mobile Phone Theft', 'Chennai', '2026-02-04', 'Handset was stolen inside a crowded train compartment between Central and Egmore stations.', 19, NULL, 'Under Investigation', 'Medium'),
('CASE-1012', 'Theft', 'Mumbai', '2025-08-19', 'Electronic tablets and office supplies were stolen from a shared co-working space over the weekend.', 31, 25, 'Closed', 'Low'),
('CASE-1013', 'Cybercrime', 'Bengaluru', '2026-04-10', 'A software engineer reported unauthorized transactions on their credit card after clicking a malicious SMS link regarding electricity bills.', 28, NULL, 'Open', 'High'),
('CASE-1014', 'Robbery', 'Delhi', '2025-12-05', 'Victim was intercepted by two masked assailants on a motorcycle near an isolated pedestrian subway and had their gold chain snatched.', 45, 23, 'Under Investigation', 'High'),
('CASE-1015', 'Vehicle Theft', 'Chennai', '2026-01-22', 'Four-wheeler sedan parked outside an apartment complex was stolen using signal-jamming equipment overnight.', 40, NULL, 'Open', 'Medium'),
('CASE-1016', 'Vandalism', 'Kochi', '2026-06-11', 'Public bus shelter glass panels and municipal streetlights damaged intentionally during late night hours.', NULL, 20, 'Closed', 'Low'),
('CASE-1017', 'Missing Person', 'Madurai', '2026-03-15', 'A college student went missing after leaving home for morning examinations; last seen near the bus terminal.', 20, NULL, 'Open', 'Critical'),
('CASE-1018', 'Drug-related offences', 'Goa', '2026-05-02', 'Seizure of contraband substances from a courier parcel destined for international transit.', 33, 35, 'Under Investigation', 'High'),
('CASE-1019', 'Theft', 'Chennai', '2026-07-08', 'Cash drawer tampered with and money stolen from a small grocery store after shutter was pried open.', 62, NULL, 'Open', 'Medium'),
('CASE-1020', 'Mobile Phone Theft', 'Delhi', '2026-06-25', 'Device was snatched from victim hand while waiting at a bus stop by a pillion rider on a scooter.', 22, 19, 'Open', 'Medium'),

('CASE-1021', 'Theft', 'Mumbai', '2026-06-12', 'A high-end DSLR camera and lenses were stolen from a photography studio during an evening event.', 34, NULL, 'Open', 'Medium'),
('CASE-1022', 'Cybercrime', 'Bengaluru', '2026-07-14', 'Ransomware attack encrypted critical files of a mid-sized accounting consultancy demanding cryptocurrency payment.', NULL, NULL, 'Under Investigation', 'Critical'),
('CASE-1023', 'Burglary', 'Hyderabad', '2026-04-05', 'Thieves entered a locked residential apartment on the third floor through the balcony and stole jewelry worth several lakhs.', 52, 29, 'Open', 'High'),
('CASE-1024', 'Assault', 'Delhi', '2026-03-20', 'Pedestrian was assaulted during an attempted mugging in an unlit alleyway near a metro station.', 27, 24, 'Under Investigation', 'High'),
('CASE-1025', 'Vehicle Theft', 'Bengaluru', '2026-02-18', 'Electric scooter stolen from office basement parking lot during working hours.', 26, NULL, 'Closed', 'Low'),
('CASE-1026', 'Fraud', 'Mumbai', '2026-05-19', 'Senior citizen defrauded by impersonators posing as electricity board officials demanding immediate bill clearance.', 68, NULL, 'Under Investigation', 'High'),
('CASE-1027', 'Theft', 'Kolkata', '2025-09-12', 'Bicycle stolen from apartment compound despite being locked to the metal railing.', 16, NULL, 'Closed', 'Low'),
('CASE-1028', 'Mobile Phone Theft', 'Madurai', '2026-01-30', 'Cell phone stolen from a devotee coat pocket inside a crowded temple festival corridor.', 55, NULL, 'Open', 'Low'),
('CASE-1029', 'Vehicle Theft', 'Pune', '2026-03-12', 'Delivery van carrying consumer electronics was driven away when driver stepped out momentarily.', 36, 31, 'Under Investigation', 'Medium'),
('CASE-1030', 'Robbery', 'Chennai', '2026-06-19', 'Armed robbery at a convenience store where cash register was looted at knifepoint during late night shift.', 25, 27, 'Under Investigation', 'High'),

('CASE-1031', 'Theft', 'Mumbai', '2026-01-14', 'Wallets and credit cards stolen from gym lockers after unauthorized access to the changing rooms.', 30, NULL, 'Under Investigation', 'Low'),
('CASE-1032', 'Assault', 'Bengaluru', '2026-02-28', 'Security guard at a commercial tech park assaulted by unruly trespassers refusing to show identification.', 48, 22, 'Closed', 'Medium'),
('CASE-1033', 'Cybercrime', 'Hyderabad', '2026-05-22', 'Data breach reported by an e-commerce platform involving unauthorized extraction of customer email addresses.', NULL, NULL, 'Open', 'Critical'),
('CASE-1034', 'Missing Person', 'Delhi', '2026-04-02', 'Elderly individual suffering from dementia went missing from a neighborhood park.', 74, NULL, 'Closed', 'High'),
('CASE-1035', 'Burglary', 'Coimbatore', '2026-06-01', 'Locked textile warehouse broken into overnight; substantial stock of premium silk sarees stolen.', 53, NULL, 'Open', 'High'),
('CASE-1036', 'Mobile Phone Theft', 'Kochi', '2026-03-25', 'Tourist mobile phone lifted from beach recliner table while taking a swim.', 29, NULL, 'Open', 'Low'),
('CASE-1037', 'Fraud', 'Delhi', '2026-07-02', 'Identity theft victim discovered multiple unauthorized bank loan accounts opened in their name using forged Aadhaar copies.', 39, NULL, 'Under Investigation', 'High'),
('CASE-1038', 'Vandalism', 'Pune', '2025-10-18', 'Multiple parked cars keyed and windshields cracked in a residential society driveway.', NULL, 18, 'Closed', 'Low'),
('CASE-1039', 'Drug-related offences', 'Chennai', '2026-06-29', 'Peddling illicit pharmaceutical tablets near a university campus; suspect apprehended in possession of 500 strips.', 21, 24, 'Closed', 'High'),
('CASE-1040', 'Theft', 'Hyderabad', '2026-03-14', 'Copper wiring and construction power cables stolen from an active infrastructure metro rail site.', NULL, NULL, 'Open', 'Medium'),

('CASE-1041', 'Robbery', 'Kolkata', '2026-04-18', 'Jewellery showroom raided by three individuals brandishing firearms before escaping on two-wheelers.', 44, 32, 'Under Investigation', 'Critical'),
('CASE-1042', 'Vehicle Theft', 'Delhi', '2026-07-10', 'Luxury SUV stolen from outside a five-star hotel valet drop-off zone.', 41, NULL, 'Open', 'High'),
('CASE-1043', 'Mobile Phone Theft', 'Bengaluru', '2026-05-08', 'Device snatched from a pedestrian while crossing the road at a busy traffic junction.', 23, 20, 'Open', 'Medium'),
('CASE-1044', 'Theft', 'Mumbai', '2026-07-21', 'Luggage stolen from the luggage compartment of an interstate express bus upon arrival at the terminal.', 27, NULL, 'Under Investigation', 'Medium'),
('CASE-1045', 'Burglary', 'Madurai', '2026-05-11', 'Ancestral house broken into while family was away on pilgrimage; silver vessels and antique clocks missing.', 63, NULL, 'Open', 'Medium'),
('CASE-1046', 'Cybercrime', 'Chennai', '2026-02-17', 'Business email compromise incident led to an erroneous wire transfer of company funds to an offshore bank.', 50, NULL, 'Under Investigation', 'Critical'),
('CASE-1047', 'Assault', 'Pune', '2026-01-09', 'Customer assaulted a restaurant manager over food order dispute, causing fractures.', 35, 29, 'Closed', 'High'),
('CASE-1048', 'Vehicle Theft', 'Coimbatore', '2026-04-29', 'Two-wheeler stolen from the railway station daily parking lot with broken steering lock.', 33, NULL, 'Open', 'Low'),
('CASE-1049', 'Fraud', 'Kochi', '2026-03-03', 'Fake job consultancy swindled overseas job aspirants by collecting processing fees for non-existent Gulf visas.', 26, 43, 'Under Investigation', 'High'),
('CASE-1050', 'Missing Person', 'Chennai', '2026-06-30', 'Teenager went missing from school premises after afternoon dismissal; traced safe after 48 hours.', 15, NULL, 'Closed', 'High'),

('CASE-1051', 'Theft', 'Chennai', '2025-10-24', 'Gold chain snatched from an elderly lady taking a morning walk on a quiet residential avenue.', 66, 21, 'Closed', 'Medium'),
('CASE-1052', 'Mobile Phone Theft', 'Hyderabad', '2026-06-17', 'Mobile handset slipped from a pocket while boarding a packed municipal bus during evening rush hour.', 22, NULL, 'Open', 'Low'),
('CASE-1053', 'Cybercrime', 'Delhi', '2026-03-11', 'Fake customer care hotline number on search engine led victim to install a screen-sharing app, emptying bank account.', 49, NULL, 'Under Investigation', 'High'),
('CASE-1054', 'Robbery', 'Bengaluru', '2026-02-01', 'Delivery boy held up by three armed youths in an isolated lane and deprived of delivery cash collection and packages.', 24, 21, 'Closed', 'High'),
('CASE-1055', 'Vehicle Theft', 'Madurai', '2026-05-27', 'Commercial auto-rickshaw stolen while parked outside driver residence overnight.', 42, NULL, 'Open', 'Low'),
('CASE-1056', 'Burglary', 'Kolkata', '2026-06-08', 'Electronics showroom shutter pried open; 40 branded television sets and audio systems carted away in a truck.', 51, NULL, 'Under Investigation', 'High'),
('CASE-1057', 'Assault', 'Chennai', '2026-04-14', 'Road rage incident escalated into assault with an iron rod following a minor collision between two cars.', 36, 31, 'Under Investigation', 'High'),
('CASE-1058', 'Drug-related offences', 'Delhi', '2026-01-25', 'Commercial quantity of banned narcotics recovered from a concealed compartment in an interstate transport truck.', 38, 40, 'Closed', 'Critical'),
('CASE-1059', 'Fraud', 'Pune', '2026-07-05', 'Ponzi crypto scheme cheated over 200 investors by promising guaranteed 15% monthly returns.', 46, 39, 'Under Investigation', 'Critical'),
('CASE-1060', 'Vandalism', 'Bengaluru', '2026-03-18', 'Graffiti sprayed across public heritage monument walls and informational signage defaced.', NULL, 19, 'Closed', 'Low'),

('CASE-1061', 'Mobile Phone Theft', 'Mumbai', '2026-05-23', 'Smartphone pickpocketed inside a crowded local train between Dadar and Kurla stations.', 27, NULL, 'Open', 'Medium'),
('CASE-1062', 'Theft', 'Delhi', '2026-02-12', 'Valuable copper pipes and air conditioner outdoor compressors stolen from a commercial office roof.', 43, NULL, 'Open', 'Medium'),
('CASE-1063', 'Cybercrime', 'Kochi', '2026-04-19', 'Social media account of a public figure hacked to solicit donations under the guise of emergency medical aid.', 34, NULL, 'Closed', 'Medium'),
('CASE-1064', 'Robbery', 'Hyderabad', '2026-07-09', 'Night-time robbery at an automated teller machine (ATM) kiosk; security guard overpowered and cash cassettes tampered.', 55, 28, 'Under Investigation', 'Critical'),
('CASE-1065', 'Vehicle Theft', 'Kolkata', '2026-03-01', 'Motorbike parked in hospital visitor lot stolen in broad daylight.', 29, NULL, 'Open', 'Low'),
('CASE-1066', 'Burglary', 'Delhi', '2025-11-28', 'Doctor clinic broken into during night; diagnostic equipment and safe containing cash stolen.', 60, NULL, 'Closed', 'High'),
('CASE-1067', 'Assault', 'Madurai', '2026-06-22', 'Dispute among market vendors over stall allocation resulted in grievous physical assault.', 41, 37, 'Open', 'High'),
('CASE-1068', 'Missing Person', 'Bengaluru', '2026-01-12', 'A young software developer failed to return home from an evening jogging trail.', 25, NULL, 'Under Investigation', 'Critical'),
('CASE-1069', 'Fraud', 'Chennai', '2026-05-16', 'Real estate fraud where multiple buyers were sold duplicate title deeds for the same residential plot.', 56, 52, 'Under Investigation', 'High'),
('CASE-1070', 'Theft', 'Coimbatore', '2026-07-18', 'Motor pump set and irrigation electrical starters stolen from farm field shed overnight.', 49, NULL, 'Open', 'Low'),

('CASE-1071', 'Mobile Phone Theft', 'Pune', '2026-04-07', 'Mobile phone snatched from a passenger sitting next to an open bus window at a signal stop.', 20, 22, 'Open', 'Medium'),
('CASE-1072', 'Vehicle Theft', 'Hyderabad', '2026-06-28', 'Brand new scooter stolen from shopping mall two-wheeler basement parking.', 31, NULL, 'Open', 'Medium'),
('CASE-1073', 'Cybercrime', 'Mumbai', '2026-01-29', 'Sim-swap fraud resulted in unauthorized net-banking debit of company accounts while owner was travelling abroad.', 54, NULL, 'Under Investigation', 'High'),
('CASE-1074', 'Robbery', 'Madurai', '2026-03-08', 'Highway robbery targeting a private courier vehicle transporting bullion; vehicle intercepted and looted.', 39, 34, 'Under Investigation', 'Critical'),
('CASE-1075', 'Burglary', 'Chennai', '2026-05-04', 'Locked apartment in a gated community burgled while occupants were away on vacation; diamond jewelry stolen.', 48, NULL, 'Open', 'High'),
('CASE-1076', 'Assault', 'Kochi', '2026-02-15', 'Ferry passenger assaulted a ticket inspector following an argument over concession passes.', 45, 26, 'Closed', 'Low'),
('CASE-1077', 'Drug-related offences', 'Bengaluru', '2026-07-01', 'Illegal rave party busted on city outskirts; synthetic drugs seized and organizers detained.', 28, 30, 'Under Investigation', 'High'),
('CASE-1078', 'Theft', 'Mumbai', '2026-03-19', 'Designer wristwatch stolen from a hotel guest room safe during housekeeping hours.', 42, 27, 'Closed', 'Medium'),
('CASE-1079', 'Vandalism', 'Delhi', '2026-06-15', 'Unruly crowd damaged public transport buses and broken windshields following a local protest.', NULL, 23, 'Under Investigation', 'Medium'),
('CASE-1080', 'Fraud', 'Kolkata', '2026-02-22', 'Cheque cloning scam targeting a charitable trust account withdrawing substantial sums across different branches.', 65, NULL, 'Under Investigation', 'High'),

('CASE-1081', 'Mobile Phone Theft', 'Chennai', '2026-07-12', 'Handset pulled from a student backpack while standing in a cinema ticket queue.', 19, NULL, 'Open', 'Low'),
('CASE-1082', 'Vehicle Theft', 'Delhi', '2026-05-18', 'Delivery motorcycle stolen while delivery partner was upstairs handing over a grocery order.', 25, NULL, 'Open', 'Low'),
('CASE-1083', 'Cybercrime', 'Bengaluru', '2026-06-20', 'Matrimonial website scam where victim was cheated of funds under pretext of customs clearance for expensive overseas gifts.', 33, 38, 'Under Investigation', 'Medium'),
('CASE-1084', 'Robbery', 'Pune', '2026-01-11', 'Pedestrian threatened with a knife at midnight near an IT corridor and stripped of purse, watch, and mobile phone.', 28, 24, 'Closed', 'High'),
('CASE-1085', 'Burglary', 'Kochi', '2026-04-26', 'Pharmacy store entered through false ceiling; prescription narcotics and cash register stolen.', 52, NULL, 'Under Investigation', 'High'),
('CASE-1086', 'Assault', 'Hyderabad', '2026-07-06', 'Violent brawl in a pub resulting in severe head injuries to two patrons.', 26, 25, 'Under Investigation', 'High'),
('CASE-1087', 'Missing Person', 'Kolkata', '2026-03-05', 'School teacher went missing on way back home from school; found safe in another district after memory lapse episode.', 48, NULL, 'Closed', 'Medium'),
('CASE-1088', 'Theft', 'Madurai', '2026-02-16', 'Motor cycle battery and spare parts stolen from multiple two-wheelers parked in open lot.', 37, NULL, 'Closed', 'Low'),
('CASE-1089', 'Fraud', 'Bengaluru', '2026-07-22', 'Fake cryptocurrency trading bot advertised on social media collected deposits and shut down abruptly.', 30, NULL, 'Under Investigation', 'High'),
('CASE-1090', 'Drug-related offences', 'Mumbai', '2026-06-05', 'Narcotics control squad seized foreign postal package containing illicit psychotropic pills at cargo terminal.', 35, NULL, 'Under Investigation', 'High'),

('CASE-1091', 'Mobile Phone Theft', 'Delhi', '2026-04-15', 'Phone taken from coat pocket inside an overcrowded metro coach on the Yellow Line.', 27, NULL, 'Open', 'Medium'),
('CASE-1092', 'Vehicle Theft', 'Chennai', '2026-03-31', 'Auto rickshaw stolen from outside a hospital entrance while driver accompanied a patient.', 46, NULL, 'Open', 'Low'),
('CASE-1093', 'Theft', 'Pune', '2026-06-27', 'Laptop and audio headphones stolen from a library reading room while student took a 10-minute break.', 21, NULL, 'Open', 'Low'),
('CASE-1094', 'Cybercrime', 'Hyderabad', '2026-01-08', 'Fake electricity bill SMS scam targeted residential welfare association members.', 58, NULL, 'Closed', 'Medium'),
('CASE-1095', 'Robbery', 'Coimbatore', '2026-05-15', 'Cash courier intercepted on bypass road; briefcase with trading cash snatched after pepper spray attack.', 38, 29, 'Under Investigation', 'High'),
('CASE-1096', 'Burglary', 'Bengaluru', '2026-03-22', 'Ground floor electronics warehouse broken into; high-end gaming laptops and graphics cards stolen.', 40, NULL, 'Open', 'High'),
('CASE-1097', 'Assault', 'Delhi', '2026-07-16', 'Toll booth operator assaulted by occupants of an unregistered vehicle refusing to pay toll fee.', 31, 26, 'Closed', 'Medium'),
('CASE-1098', 'Vandalism', 'Madurai', '2026-04-09', 'Public park fitness equipment and children play swing damaged maliciously overnight.', NULL, 17, 'Closed', 'Low'),
('CASE-1099', 'Missing Person', 'Chennai', '2026-07-04', '14-year-old child reported missing after tuition classes; safely reunited within 12 hours.', 14, NULL, 'Closed', 'High'),
('CASE-1100', 'Theft', 'Kochi', '2026-05-28', 'Outboard boat motor stolen from a fishing vessel berthed at the harbor wharf.', 50, NULL, 'Open', 'Medium'),

('CASE-1101', 'Mobile Phone Theft', 'Bengaluru', '2026-07-07', 'iPhone stolen from woman handbag while dining at a crowded rooftop restaurant.', 26, 23, 'Under Investigation', 'Medium'),
('CASE-1102', 'Vehicle Theft', 'Mumbai', '2026-02-25', 'Vintage convertible car stolen from private collector garage in South Mumbai.', 61, NULL, 'Under Investigation', 'High'),
('CASE-1103', 'Fraud', 'Chennai', '2026-06-16', 'Job seekers scammed with forged appointment letters for government railway positions.', 24, 45, 'Under Investigation', 'High'),
('CASE-1104', 'Drug-related offences', 'Kolkata', '2026-04-12', 'Peddling synthetic narcotics outside an educational institute; two suspects arrested with 120 grams contraband.', 20, 22, 'Closed', 'High'),
('CASE-1105', 'Cybercrime', 'Delhi', '2026-07-23', 'Corporate cloud infrastructure compromised with illicit crypto-mining scripts executed without authorization.', NULL, NULL, 'Under Investigation', 'High');
